import type { ModelEntry } from './types'

export const FALLBACK_CATALOG: ModelEntry[] = [
  // ─── WebLLM / MLC models ─────────────────────────────────────────────────
  {
    id: 'phi-3.5-vision-instruct-q4f16-mlc',
    name: 'Phi-3.5 Vision Instruct',
    provider: 'Microsoft',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Phi-3.5-vision-instruct-q4f16_1-MLC',
    modelId: 'Phi-3.5-vision-instruct-q4f16_1-MLC',
    sizeLabel: '~3.5 GB',
    estimatedRam: 5200,
    estimatedVram: 4200,
    quantization: 'q4f16',
    parameterSize: '4.2B',
    architecture: 'Phi3VForCausalLM',
    tags: ['vision', 'multimodal', 'instruct'],
    recommended: false,
    experimental: true,
    disabled: false,
    description: "Microsoft's Phi-3.5 Vision — a multimodal model that can analyze images. Attach a photo in chat and ask about it. Large download; requires a capable GPU.",
    warnings: ['Large model (~3.5 GB). Needs a GPU with sufficient VRAM.', 'Vision inference is slower than text-only.'],
    license: 'MIT',
    sourceUrl: 'https://huggingface.co/microsoft/Phi-3.5-vision-instruct',
    supportsVision: true,
  },
  {
    id: 'smollm2-360m-instruct-q4f16-mlc',
    name: 'SmolLM2 360M Instruct',
    provider: 'HuggingFace',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/SmolLM2-360M-Instruct-q4f16_1-MLC',
    modelId: 'SmolLM2-360M-Instruct-q4f16_1-MLC',
    sizeLabel: '~230 MB',
    estimatedRam: 512,
    estimatedVram: 512,
    quantization: 'q4f16',
    parameterSize: '360M',
    architecture: 'LlamaForCausalLM',
    tags: ['small', 'instruct', 'fast'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Tiny but capable instruction-following model. Best starting point for testing WebGPU inference.',
    warnings: [],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct',
  },
  {
    id: 'smollm2-1.7b-instruct-q4f16-mlc',
    name: 'SmolLM2 1.7B Instruct',
    provider: 'HuggingFace',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/SmolLM2-1.7B-Instruct-q4f16_1-MLC',
    modelId: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC',
    sizeLabel: '~1.0 GB',
    estimatedRam: 1500,
    estimatedVram: 1500,
    quantization: 'q4f16',
    parameterSize: '1.7B',
    architecture: 'LlamaForCausalLM',
    tags: ['small', 'instruct'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Excellent small model with strong instruction following. Good balance of size and capability.',
    warnings: [],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct',
  },
  {
    id: 'qwen2.5-0.5b-instruct-q4f16-mlc',
    name: 'Qwen2.5 0.5B Instruct',
    provider: 'Alibaba Cloud',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC',
    modelId: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC',
    sizeLabel: '~400 MB',
    estimatedRam: 600,
    estimatedVram: 600,
    quantization: 'q4f16',
    parameterSize: '0.5B',
    architecture: 'Qwen2ForCausalLM',
    tags: ['tiny', 'instruct', 'multilingual'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Ultra-compact model from Alibaba. Surprisingly capable for its size, with multilingual support.',
    warnings: [],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct',
  },
  {
    id: 'qwen2.5-1.5b-instruct-q4f16-mlc',
    name: 'Qwen2.5 1.5B Instruct',
    provider: 'Alibaba Cloud',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Qwen2.5-1.5B-Instruct-q4f16_1-MLC',
    modelId: 'Qwen2.5-1.5B-Instruct-q4f16_1-MLC',
    sizeLabel: '~1.0 GB',
    estimatedRam: 1200,
    estimatedVram: 1200,
    quantization: 'q4f16',
    parameterSize: '1.5B',
    architecture: 'Qwen2ForCausalLM',
    tags: ['instruct', 'multilingual', 'coding'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Strong 1.5B model with good coding and reasoning ability. Supports multiple languages.',
    warnings: [],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct',
  },
  {
    id: 'llama3.2-1b-instruct-q4f16-mlc',
    name: 'Llama 3.2 1B Instruct',
    provider: 'Meta',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Llama-3.2-1B-Instruct-q4f16_1-MLC',
    modelId: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
    sizeLabel: '~700 MB',
    estimatedRam: 1000,
    estimatedVram: 1000,
    quantization: 'q4f16',
    parameterSize: '1B',
    architecture: 'LlamaForCausalLM',
    tags: ['instruct', 'meta'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Meta\'s compact Llama 3.2 1B model. Fast inference with good quality for its size.',
    warnings: [],
    license: 'Llama 3.2 Community License',
    sourceUrl: 'https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct',
  },
  {
    id: 'llama3.2-3b-instruct-q4f16-mlc',
    name: 'Llama 3.2 3B Instruct',
    provider: 'Meta',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Llama-3.2-3B-Instruct-q4f16_1-MLC',
    modelId: 'Llama-3.2-3B-Instruct-q4f16_1-MLC',
    sizeLabel: '~2.0 GB',
    estimatedRam: 2500,
    estimatedVram: 2500,
    quantization: 'q4f16',
    parameterSize: '3B',
    architecture: 'LlamaForCausalLM',
    tags: ['instruct', 'meta', 'capable'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Meta\'s Llama 3.2 3B — a strong mid-size model with solid reasoning and conversation quality.',
    warnings: ['Requires ~2 GB of VRAM/RAM. May be slow on lower-end hardware.'],
    license: 'Llama 3.2 Community License',
    sourceUrl: 'https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct',
  },
  {
    id: 'gemma-2-2b-it-q4f16-mlc',
    name: 'Gemma 2 2B Instruct',
    provider: 'Google',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/gemma-2-2b-it-q4f16_1-MLC',
    modelId: 'gemma-2-2b-it-q4f16_1-MLC',
    sizeLabel: '~1.5 GB',
    estimatedRam: 2000,
    estimatedVram: 2000,
    quantization: 'q4f16',
    parameterSize: '2B',
    architecture: 'Gemma2ForCausalLM',
    tags: ['instruct', 'google', 'capable'],
    recommended: true,
    experimental: false,
    disabled: false,
    description: 'Google\'s Gemma 2 2B — strong multilingual support and instruction following. A great all-round starter for its size.',
    warnings: [],
    license: 'Gemma Terms of Use',
    sourceUrl: 'https://huggingface.co/google/gemma-2-2b-it',
  },
  {
    id: 'phi-3.5-mini-instruct-q4f16-mlc',
    name: 'Phi-3.5 Mini Instruct',
    provider: 'Microsoft',
    engine: 'webllm',
    format: 'mlc',
    repo: 'mlc-ai/Phi-3.5-mini-instruct-q4f16_1-MLC',
    modelId: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
    sizeLabel: '~2.3 GB',
    estimatedRam: 3000,
    estimatedVram: 3000,
    quantization: 'q4f16',
    parameterSize: '3.8B',
    architecture: 'Phi3ForCausalLM',
    tags: ['instruct', 'microsoft', 'coding', 'reasoning'],
    recommended: false,
    experimental: false,
    disabled: false,
    description: 'Microsoft\'s Phi-3.5 Mini — strong coding and reasoning performance despite compact size.',
    warnings: ['Requires ~3 GB RAM/VRAM. May be slow on integrated graphics.'],
    license: 'MIT',
    sourceUrl: 'https://huggingface.co/microsoft/Phi-3.5-mini-instruct',
  },
  // ─── GGUF models via Wllama ───────────────────────────────────────────────
  {
    id: 'smollm2-360m-q4km-gguf',
    name: 'SmolLM2 360M Q4_K_M (GGUF)',
    provider: 'HuggingFace',
    engine: 'wllama',
    format: 'gguf',
    repo: 'HuggingFaceTB/SmolLM2-360M-Instruct-GGUF',
    file: 'smollm2-360m-instruct-q4_k_m.gguf',
    modelId: 'HuggingFaceTB/SmolLM2-360M-Instruct-GGUF',
    sizeLabel: '~230 MB',
    estimatedRam: 400,
    estimatedVram: 0,
    quantization: 'q4_k_m',
    parameterSize: '360M',
    architecture: 'LlamaForCausalLM',
    tags: ['small', 'instruct', 'gguf', 'cpu'],
    recommended: true,
    experimental: true,
    disabled: false,
    description: 'SmolLM2 360M in GGUF format for CPU inference via Wllama. Good for devices without WebGPU.',
    warnings: [
      'GGUF inference via Wllama is experimental and CPU-bound.',
      'Inference will be significantly slower than WebLLM with WebGPU.',
    ],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF',
  },
  {
    id: 'qwen2.5-0.5b-q4km-gguf',
    name: 'Qwen2.5 0.5B Q4_K_M (GGUF)',
    provider: 'Alibaba Cloud',
    engine: 'wllama',
    format: 'gguf',
    repo: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF',
    file: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
    modelId: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF',
    sizeLabel: '~400 MB',
    estimatedRam: 600,
    estimatedVram: 0,
    quantization: 'q4_k_m',
    parameterSize: '0.5B',
    architecture: 'Qwen2ForCausalLM',
    tags: ['tiny', 'instruct', 'gguf', 'cpu', 'multilingual'],
    recommended: true,
    experimental: true,
    disabled: false,
    description: 'Qwen2.5 0.5B GGUF for CPU-only environments. Compact and multilingual.',
    warnings: [
      'GGUF/Wllama is experimental.',
      'CPU inference only — significantly slower than WebLLM.',
    ],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF',
  },
  {
    id: 'tinyllama-1.1b-q4km-gguf',
    name: 'TinyLlama 1.1B Chat Q4_K_M (GGUF)',
    provider: 'Zhang Peiyuan',
    engine: 'wllama',
    format: 'gguf',
    repo: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF',
    file: 'tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
    modelId: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF',
    sizeLabel: '~670 MB',
    estimatedRam: 1000,
    estimatedVram: 0,
    quantization: 'q4_k_m',
    parameterSize: '1.1B',
    architecture: 'LlamaForCausalLM',
    tags: ['small', 'chat', 'gguf', 'cpu'],
    recommended: false,
    experimental: true,
    disabled: false,
    description: 'Classic TinyLlama chat model in GGUF format. Runs on CPU via Wllama.',
    warnings: [
      'GGUF/Wllama is experimental.',
      'Large file — may take significant time to download.',
    ],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0',
  },
  {
    id: 'smolmoe-4x360m-gguf',
    name: 'SmolMoE 4×360M Instruct (GGUF)',
    provider: 'HuggingFace',
    engine: 'wllama',
    format: 'gguf',
    repo: 'HuggingFaceTB/SmolMoE-4x360M-Instruct-GGUF',
    file: 'smolmoe-4x360m-instruct-q4_k_m.gguf',
    modelId: 'HuggingFaceTB/SmolMoE-4x360M-Instruct-GGUF',
    sizeLabel: '~900 MB',
    estimatedRam: 1500,
    estimatedVram: 0,
    quantization: 'q4_k_m',
    parameterSize: '4×360M MoE',
    architecture: 'MoE',
    tags: ['moe', 'instruct', 'gguf', 'experimental'],
    recommended: false,
    experimental: true,
    disabled: false,
    description: 'Mixture-of-Experts model with 4 expert networks. May not work in all browsers due to memory requirements.',
    warnings: [
      'MoE architecture requires more RAM than parameter count suggests.',
      'Experimental: may fail in browsers with strict memory limits.',
      'GGUF/Wllama is experimental.',
    ],
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/HuggingFaceTB/SmolMoE-4x360M-Instruct',
  },
]
